### ISSUE TITLE
Add ability to save snap image to file with metadata

### ISSUE THREAD

**Issue by mickp** [microscope-cockpit/cockpit#391]
From either right click on image, or context menu on snap button that lists channels

**Comment by iandobbie** [comment]
There is partial support, you can now save a snapped image but you dont get the meta data.

**Comment by iandobbie** [comment]
This relates to issues #538,  #629 and #676 as they would all benefit from the additional meta data, howveer it is not trivial as we need to extend the image object to include this meta data. It would also help if we want to make colour images/mosaics.

**Comment by iandobbie** [comment]
Saved snapped images now get pixel size and xyz position. We should probably also add the relevant extended header info as well as exposure time and active light sources probably in the free text fields.
