### ISSUE TITLE
getNumberDialogs are never destroyed

### ISSUE THREAD

**Issue by juliomateoslangerak** [microscope-cockpit/cockpit#666]
Every time one sets the diffraction angle or generates a new sequence on the SLM a new menu item is added to the Windows menu.

**Comment by juliomateoslangerak** [comment]
Yes, they are top-level windows. I don't know if that is what you mean.
This is what I see after setting twice diffraction angle and creating twice a sequence
![image](https://user-images.githubusercontent.com/7799110/89020674-95451180-d31f-11ea-9f3a-c10271d57f63.png)

**Comment by carandraug** [comment]
That confirms it. The dialogs from `cockpit.gui.dialogs.getNumberDialog` are not destroyed after being used but they should. This can be tested without the boulder SLM, like so:

```
from cockpit.gui.dialogs import getNumberDialog
val = getNumberDialog.getNumberFromUser(None, 'Title', 'prompt', 77)
# Note that after been closed, there is a GetNumberDialog still around (it should not)
for w in wx.GetTopLevelWindows(): print(w)

# in comparison, if one uses the real wx GetX dialog, the dialog disappears after been used
import wx
val = wx.GetNumberFromUser('message', 'prompt', 'caption', 77)
for w in wx.GetTopLevelWindows(): print(w)
```

I guess one can fix the getNumberDialog but an alternative is to use one of the `wx.Get*FromUser`. There isn't one in wx to get a floating point value though.

**Comment by carandraug** [comment]
Now fixed by calling `Destroy` after being done with the dialog. Closing as fixed.
