### ISSUE TITLE
New release needed?

### ISSUE THREAD

**Issue by iandobbie** [microscope-cockpit/cockpit#829]
With the recent issue relating to cockpit and microscope version incompatibility I think we need to release new versions of both Cockpit and Microscope. Maybe we should have a plan to release new versions on  a set schedule. 

Any thoughts?

**Comment by juliomateoslangerak** [comment]
I thought we might profit from this release to change a number of things
- Black our code #649
- We probaly should use pre-commit to configure the 'blacking' of code before any commit.
- Maybe use isort in a pre-commit too
- I'm currently using poetry as a package managment system in another project. It's very nice

**Comment by iandobbie** [comment]
David produced a new release on pypi on 2024-01-10, along with a synchronized release of python-microscope. Closing as complete
