### ISSUE TITLE
Incorrect server entries in depot config fail silently. 

### ISSUE THREAD

**Issue by iandobbie** [microscope-cockpit/cockpit#872]
I had a typo in my server ip address and my cockpit config appeared to work fine except all data devices (cameras, value loggers etc...) failed to return any data totally silently.

Can we either check the server creation succeeds, check pyro connections back to it work, or maybe both.

**Comment by carandraug** [comment]
There was an exception raise by Pyro but because we're using futures and not checking the return value from finalizeInitialization, these were never raised on the main thread. This is now fixed (I've added a check for exceptions in all devices and handlers) in bd688533f4129b8. Closing as fixed.
