### ISSUE TITLE
SIM experiment is using the longest wavelength to set the SIM patterns

### ISSUE THREAD

**Issue by juliomateoslangerak** [microscope-cockpit/cockpit#888]
Looking into the code of structuredIllumination.py I realized that the experiment is only taking the longest wavelength to send to the SLM for SIM pattern generation. Did I get this wrong? Is there a particular reason for this?

**Comment by iandobbie** [comment]
Hi Julio

That should only be in simultaneous mode. Certainly on the Diamond CryoSIM it generates different stripe widths for different wavelengths.

Ian
Sent from my iPhone

On 22 Dec 2023, at 04:04, Julio Mateos Langerak ***@***.***> wrote:

﻿

Looking into the code of structuredIllumination.py I realized that the experiment is only taking the longest wavelength to send to the SLM for SIM pattern generation. Did I get this wrong? Is there a particular reason for this?

**Comment by juliomateoslangerak** [comment]
Right,
I looked back and this is in the simultaneous mode. Sorry.

Closing
